// Generated by CoffeeScript 1.6.2
(function() {
  var CATMAP, onFeatureSelect, onFeatureUnselect;

  CATMAP = {};

  this.CATMAP = CATMAP;

  CATMAP.load_map = function(map_div_name) {
    var center, christchurch, controls, geoProj, ghyb, gmap, gsat, gterr, image, kmlDir, latLonBounds4km, layerSwitcher, map, mercProj, mtsat4kmImages, mtsat4kmLayer, mtsatBounds4km, multiplier, multipliers, osm, _i, _j, _len, _len1;

    geoProj = new OpenLayers.Projection("EPSG:4326");
    mercProj = new OpenLayers.Projection("EPSG:900913");
    layerSwitcher = new OpenLayers.Control.LayerSwitcher;
    controls = [new OpenLayers.Control.KeyboardDefaults, new OpenLayers.Control.Graticule, layerSwitcher, new OpenLayers.Control.Navigation];
    map = new OpenLayers.Map(map_div_name, {
      controls: controls
    });
    layerSwitcher.maximizeControl();
    CATMAP.map = map;
    osm = new OpenLayers.Layer.OSM();
    map.addLayer(osm);
    gterr = new OpenLayers.Layer.Google("Google Terrain", {
      type: google.maps.MapTypeId.TERRAIN
    });
    gmap = new OpenLayers.Layer.Google("Google Streets", {
      numZoomLevels: 20
    });
    ghyb = new OpenLayers.Layer.Google("Google Hybrid", {
      type: google.maps.MapTypeId.HYBRID,
      numZoomLevels: 20
    });
    gsat = new OpenLayers.Layer.Google("Google Satellite", {
      type: google.maps.MapTypeId.SATELLITE,
      numZoomLevels: 22
    });
    map.addLayers([gterr, gmap, ghyb, gsat]);
    christchurch = new OpenLayers.LonLat(172.620278, -43.53);
    center = christchurch;
    map.setCenter(center.transform(geoProj, mercProj), 5);
    kmlDir = "kml";
    multipliers = [-1, 0];
    mtsat4kmImages = ['img/ops.MTSAT-2.201308012032.ch1_vis.jpg', 'img/ops.MTSAT-2.201308012032.ch2_thermal_IR.jpg', 'img/ops.MTSAT-2.201308012032.ch4_water_vapor.jpg'];
    for (_i = 0, _len = multipliers.length; _i < _len; _i++) {
      multiplier = multipliers[_i];
      latLonBounds4km = [130.5 + (360 * multiplier), -63.5, 360 - 150.5 + (360 * multiplier), -17.84];
      mtsatBounds4km = new OpenLayers.Bounds(latLonBounds4km).transform(geoProj, mercProj);
      for (_j = 0, _len1 = mtsat4kmImages.length; _j < _len1; _j++) {
        image = mtsat4kmImages[_j];
        mtsat4kmLayer = new OpenLayers.Layer.Image(image, image, mtsatBounds4km, new OpenLayers.Size(2200, 1800), {
          isBaseLayer: false,
          alwaysInRange: true,
          wrapDateLine: true
        });
        map.addLayers([mtsat4kmLayer]);
        mtsat4kmLayer.setOpacity(.6);
      }
    }
    return map;
  };

  onFeatureSelect = function(event) {
    var content, feature, popup;

    feature = event.feature;
    console.log(feature);
    content = "<h2>" + feature.attributes.name + "</h2>" + feature.attributes.description;
    console.log(feature.attributes.description);
    popup = new OpenLayers.Popup.FramedCloud("chickenXXX", feature.geometry.getBounds().getCenterLonLat(), new OpenLayers.Size(100, 100), content, null, true);
    feature.popup = popup;
    return CATMAP.map.addPopup(popup);
  };

  onFeatureUnselect = function(event) {
    var feature;

    feature = event.feature;
    console.log(feature);
    if (feature.popup) {
      CATMAP.map.removePopup(feature.popup);
      feature.popup.destroy();
      return delete feature.popup;
    }
  };

}).call(this);
