// Generated by CoffeeScript 1.10.0
(function() {
  var map;

  map = map || {};

  this.map = map;

  map.init = function(divName, projectionLabel, offsetLabel) {
    var labelEl, tiles;
    if (divName == null) {
      divName = 'map';
    }
    if (projectionLabel == null) {
      projectionLabel = '3571';
    }
    if (offsetLabel == null) {
      offsetLabel = '0';
    }
    console.log('map.init()');
    labelEl = document.getElementById('projection-label');
    labelEl.innerHTML = "EPSG:" + projectionLabel;
    labelEl.innerHTML += " (" + offsetLabel + ")";
    Proj4js.defs['EPSG:3571'] = '+proj=laea +lat_0=90 +lon_0=180 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs';
    Proj4js.defs['EPSG:3572'] = '+proj=laea +lat_0=90 +lon_0=-150 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs';
    Proj4js.defs['EPSG:3573'] = '+proj=laea +lat_0=90 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs';
    Proj4js.defs['EPSG:3574'] = '+proj=laea +lat_0=90 +lon_0=-40 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs';
    Proj4js.defs['EPSG:3575'] = '+proj=laea +lat_0=90 +lon_0=10 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs';
    Proj4js.defs['EPSG:3576'] = '+proj=laea +lat_0=90 +lon_0=90 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs';
    map = new OpenLayers.Map('map', {
      controls: [
        new OpenLayers.Control.Navigation, new OpenLayers.Control.PanZoomBar, new OpenLayers.Control.Attribution, new OpenLayers.Control.ScaleLine, new OpenLayers.Control.Permalink({
          anchor: true
        })
      ],
      projection: "EPSG:" + projectionLabel,
      displayProjection: 'EPSG:4326'
    });
    tiles = new OpenLayers.Layer.XYZ("EPSG:" + projectionLabel, "http://a.tiles.arcticconnect.ca/osm_" + projectionLabel + "/${z}/${x}/${y}.png", {
      projection: "EPSG:" + projectionLabel,
      maxExtent: [-3000000, -3000000, 3000000, 3000000],
      attribution: 'Map © <a href=\'http://arcticconnect.ca/\'>ArcticConnect</a>. Data © <a href=\'http://www.openstreetmap.org/\'>OpenStreetMap</a> contributors',
      numZoomLevels: 10,
      transitionEffect: 'resize'
    });
    map.addLayer(tiles);
    if (!map.getCenter()) {
      map.setCenter(new OpenLayers.LonLat(0, 0), 1);
    }
    return map.zoomTo(4);
  };

}).call(this);
